import type { Metadata } from "next";
import 'bootstrap/dist/css/bootstrap.css'
import ImportBsJS from "./importBsJS";
import { Inter } from "next/font/google";
import "./globals.css";
import "./style.css";
import Header from "./components/Header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ImportBsJS />
      <body className={inter.className}>
        <Header />
        {children}</body>
    </html>
  );
}
