import type { Metadata } from "next";
import 'bootstrap/dist/css/bootstrap.css'
import ImportBsJS from "./importBsJS";
import { Montserrat } from 'next/font/google';
import "./style.css";
import Header from "./components/Header/Header";
import Footer from "./components/Footer/Footer";

const montserrat = Montserrat({
  weight: ['300', '400', '500','600', '700'],
  subsets: ['latin'],
  display:'swap',
  variable: '--font-montserrat',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ImportBsJS />
      <body className={montserrat.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
