'use client'
import { usePathname } from 'next/navigation';
import 'bootstrap/dist/css/bootstrap.css';
import 'aos/dist/aos.css';
import ImportBsJS from "./importBsJS";
import ImportAOS from './importAOS';
import { Alkatra, Montserrat } from 'next/font/google';
import "./style.css";
import Header from "../components/Header/Header";
import Footer from "../components/Footer/Footer";

const montserrat = Montserrat({
  weight: ['300', '400', '500', '600', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-montserrat',
});

const alkatra = Alkatra({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-alkatra',
});

// export const metadata = {
//   title: "Imagine Group",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const pathname = usePathname();

  const showHeaderFooter = pathname !== '/signin' && pathname !== '/signup' && !pathname.startsWith('/admin');

  return (
    <html lang="en">
      <body className={` bg-pattern-dark ${montserrat.variable} ${alkatra.variable}`}>
        {showHeaderFooter && <Header />}
        <main className="flex-grow-1">{children}</main>
        {showHeaderFooter && <Footer />}
        <ImportBsJS />
        <ImportAOS />
      </body>
    </html>
  );
}